-- Replace '?' with NULL in multiple columns
UPDATE diabetic_data 
SET 
  race = NULLIF(race, '?'),
  gender = NULLIF(gender, '?'),
  weight = NULLIF(weight, '?'),
  payer_code = NULLIF(payer_code, '?'),
  medical_specialty = NULLIF(medical_specialty, '?'),
  diag_2 = NULLIF(diag_2, '?'),
  diag_3 = NULLIF(diag_3, '?'),
  max_glu_serum = NULLIF(max_glu_serum, '?'),
  A1Cresult = NULLIF(A1Cresult, '?'),
  metformin = NULLIF(metformin, '?'),
  repaglinide = NULLIF(repaglinide, '?'),
  nateglinide = NULLIF(nateglinide, '?'),
  chlorpropamide = NULLIF(chlorpropamide, '?'),
  glimepiride = NULLIF(glimepiride, '?'),
  acetohexamide = NULLIF(acetohexamide, '?'),
  glipizide = NULLIF(glipizide, '?'),
  glyburide = NULLIF(glyburide, '?'),
  tolbutamide = NULLIF(tolbutamide, '?'),
  pioglitazone = NULLIF(pioglitazone, '?'),
  rosiglitazone = NULLIF(rosiglitazone, '?'),
  miglitol = NULLIF(miglitol, '?'),
  acarbose = NULLIF(acarbose, '?'),
  troglitazone = NULLIF(troglitazone, '?'),
  tolazamide = NULLIF(tolazamide, '?'),
  examide = NULLIF(examide, '?'),
  citoglipton = NULLIF(citoglipton, '?'),
  insulin = NULLIF(insulin, '?'),
  `glyburide-metformin` = NULLIF(`glyburide-metformin`, '?'),
  `glipizide-metformin` = NULLIF(`glipizide-metformin`, '?'),
  `glimepiride-pioglitazone` = NULLIF(`glimepiride-pioglitazone`, '?'),
  `metformin-rosiglitazone` = NULLIF(`metformin-rosiglitazone`, '?'),
  `metformin-pioglitazone` = NULLIF(`metformin-pioglitazone`, '?'),
  `change` = NULLIF(`change`, '?'),
  diabetesMed = NULLIF(diabetesMed, '?'),
  readmitted = NULLIF(readmitted, '?');
